# Generated by Django 5.0 on 2023-12-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
